# Prática 03
## Classificação

In [1]:
import numpy as np
import h5py

from random import shuffle
from sklearn.svm import SVC
from sklearn import metrics

In [2]:
def matriz(nRows):
    matriz = []
    for i in range(nRows):
        row = []
        matriz.append(row)
    return matriz

### Roteiro I - SVM

#### LBP

In [3]:
LBPtrain = "LBPtrain.h5"

with h5py.File(LBPtrain, "r") as hdf:
    
    x = list(hdf.keys())[0]
    Featurestrain = list(hdf[x])

shuffle(Featurestrain)
    
X = matriz(10000)
y = matriz(10000)

for i, rows in enumerate(Featurestrain):
    X[i] = Featurestrain[i][:3072]
    y[i] = Featurestrain[i][3072]

In [4]:
X = X[:5000]
y = y[:5000]

In [5]:
LBPtest = "LBPtest.h5"

with h5py.File(LBPtest, "r") as hdf:
    
    x = list(hdf.keys())[0]
    Featurestest = list(hdf[x])
    
shuffle(Featurestest)
    
Xt = matriz(10000)
yt = matriz(10000)

for i, rows in enumerate(Featurestest):
    Xt[i] = Featurestest[i][:3072]
    yt[i] = Featurestest[i][3072]

In [6]:
Xt = Xt[:5000]
yt = yt[:5000]

##### Model 01 - Linear

In [7]:
clf =  SVC(probability=True, kernel='linear')

clf.fit(X, y)                         

SVC(kernel='linear', probability=True)

In [8]:
clf.predict(Xt)

array([1, 0, 0, ..., 1, 0, 0], dtype=uint8)

In [9]:
clf.score(Xt, yt)

0.7636

In [10]:
clf.predict(X)

array([0, 0, 1, ..., 0, 0, 1], dtype=uint8)

In [11]:
clf.score(X, y)

1.0

##### Model 02 - Polinomial

In [12]:
clf2 =  SVC(probability=True, kernel='poly')

clf2.fit(X, y)                         

SVC(kernel='poly', probability=True)

In [13]:
clf2.predict(Xt)

array([0, 0, 1, ..., 1, 0, 0], dtype=uint8)

In [14]:
clf2.score(Xt, yt)

0.7864

In [15]:
clf2.predict(X)

array([0, 0, 1, ..., 0, 0, 1], dtype=uint8)

In [16]:
clf2.score(X, y)

1.0

##### Model 03 - RBF

In [17]:
clf3 =  SVC(probability=True, kernel='rbf')

clf3.fit(X, y)                         

SVC(probability=True)

In [18]:
clf3.predict(Xt)

array([1, 0, 1, ..., 1, 0, 0], dtype=uint8)

In [19]:
clf3.score(Xt, yt)

0.7832

In [20]:
clf3.predict(X)

array([0, 0, 1, ..., 0, 0, 1], dtype=uint8)

In [21]:
clf3.score(X, y)

0.9706

#### GLCM

In [5]:
GLCMtrain = "GLCMtrain.h5"

with h5py.File(GLCMtrain, "r") as hdf:
    
    x = list(hdf.keys())[0]
    Featurestrain = list(hdf[x])

shuffle(Featurestrain)
    
X = matriz(10000)
y = matriz(10000)

for i, rows in enumerate(Featurestrain):
    X[i] = Featurestrain[i][:48]
    y[i] = Featurestrain[i][48]

In [6]:
X = X[:5000]
y = y[:5000]

In [7]:
GLCMtest = "GLCMtest.h5"

with h5py.File(GLCMtest, "r") as hdf:
    
    x = list(hdf.keys())[0]
    Featurestest = list(hdf[x])
    
shuffle(Featurestest)
    
Xt = matriz(10000)
yt = matriz(10000)

for i, rows in enumerate(Featurestest):
    Xt[i] = Featurestest[i][:48]
    yt[i] = Featurestest[i][48]

In [8]:
Xt = Xt[:5000]
yt = yt[:5000]

##### Model 01 - Linear

In [ ]:
#inicio do treinamento 00:25

In [47]:
clf =  SVC(probability=True, kernel='linear') 

clf.fit(X, y)                         

SVC(kernel='linear', probability=True)

In [48]:
clf.predict(Xt)

array([1, 0, 0, ..., 1, 1, 1], dtype=uint8)

In [49]:
clf.score(Xt, yt)

0.5044

In [50]:
clf.predict(X)

array([0, 1, 0, ..., 1, 1, 1], dtype=uint8)

In [51]:
clf.score(X, y)

0.5532

##### Model 02 - Polinomial

In [9]:
clf2 =  SVC(probability=True, kernel='poly')

clf2.fit(X, y)                         

SVC(kernel='poly', probability=True)

In [10]:
clf2.predict(Xt)

array([1, 1, 1, ..., 1, 0, 1], dtype=uint8)

In [11]:
clf2.score(Xt, yt)

0.9492

In [12]:
clf2.predict(X)

array([0, 1, 0, ..., 0, 0, 0], dtype=uint8)

In [13]:
clf2.score(X, y)

0.962

##### Model 03 - RBF

In [14]:
clf3 =  SVC(probability=True, kernel='rbf')

clf3.fit(X, y)                         

SVC(probability=True)

In [15]:
clf3.predict(Xt)

array([1, 0, 1, ..., 1, 0, 1], dtype=uint8)

In [16]:
clf3.score(Xt, yt)

0.9094

In [17]:
clf3.predict(X)

array([0, 1, 0, ..., 0, 0, 0], dtype=uint8)

In [18]:
clf3.score(X, y)

0.9326

#### SOBEL

In [3]:
SOBELtrain = "SOBELtrain.h5"

with h5py.File(SOBELtrain, "r") as hdf:
    
    x = list(hdf.keys())[0]
    Featurestrain = list(hdf[x])

shuffle(Featurestrain)
    
X = matriz(10000)
y = matriz(10000)

for i, rows in enumerate(Featurestrain):
    X[i] = Featurestrain[i][:6144]
    y[i] = Featurestrain[i][6144]

In [4]:
X = X[:5000]
y = y[:5000]

In [5]:
SOBELtest = "SOBELtest.h5"

with h5py.File(SOBELtest, "r") as hdf:
    
    x = list(hdf.keys())[0]
    Featurestest = list(hdf[x])
    
shuffle(Featurestest)
    
Xt = matriz(10000)
yt = matriz(10000)

for i, rows in enumerate(Featurestest):
    Xt[i] = Featurestest[i][:6144]
    yt[i] = Featurestest[i][6144]

In [6]:
Xt = Xt[:5000]
yt = yt[:5000]

##### Model 01 - Linear

In [7]:
clf =  SVC(probability=True, kernel='linear')

clf.fit(X, y)                         

SVC(kernel='linear', probability=True)

In [8]:
clf.predict(Xt)

array([1, 1, 1, ..., 0, 1, 0], dtype=uint8)

In [9]:
clf.score(Xt, yt)

0.5908

In [10]:
clf.predict(X)

array([0, 0, 1, ..., 1, 1, 1], dtype=uint8)

In [11]:
clf.score(X, y)

1.0

##### Model 02 - Polinomial

In [12]:
clf2 =  SVC(probability=True, kernel='poly')

clf2.fit(X, y)                         

SVC(kernel='poly', probability=True)

In [13]:
clf2.predict(Xt)

array([0, 1, 1, ..., 1, 1, 0], dtype=uint8)

In [14]:
clf2.score(Xt, yt)

0.655

In [15]:
clf2.predict(X)

array([0, 0, 1, ..., 1, 1, 1], dtype=uint8)

In [16]:
clf2.score(X, y)

0.9726

##### Model 03 - RBF

In [17]:
clf3 =  SVC(probability=True, kernel='rbf')

clf3.fit(X, y)                         

SVC(probability=True)

In [18]:
clf3.predict(Xt)

array([1, 1, 1, ..., 1, 1, 0], dtype=uint8)

In [19]:
clf3.score(Xt, yt)

0.6636

In [20]:
clf3.predict(X)

array([0, 0, 1, ..., 1, 1, 1], dtype=uint8)

In [21]:
clf3.score(X, y)

0.897

In [11]:
prob = clf.predict_proba(Xt)

In [12]:
prob.shape

(5000, 2)

### Roteiro II - MLP

#### LBP

#### GLCM

#### SOBEL